# Generated by Django 5.1 on 2024-08-10 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_status_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2024, 8, 10, 16, 13, 12, 485515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2024, 8, 10, 16, 13, 12, 485515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2024, 8, 10, 16, 13, 12, 485515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2024, 8, 10, 16, 13, 12, 485515, tzinfo=datetime.timezone.utc)),
        ),
    ]
